/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "app.getAppVersion", input: never, result: string } | 
        { key: "root_directory.find", input: number, result: RootDirectory | null } | 
        { key: "root_directory.findAll", input: never, result: Array<RootDirectory> },
    mutations: 
        { key: "root_directory.create", input: string, result: RootDirectory },
    subscriptions: never
};

export interface RootDirectory { id: number, path: string, createdAt: string, updatedAt: string }
